/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "mock_hardware.h"

static const char* CMockString_getADC_value = "getADC_value";

typedef struct _CMOCK_getADC_value_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  int CallOrder;

} CMOCK_getADC_value_CALL_INSTANCE;

static struct mock_hardwareInstance
{
  int getADC_value_IgnoreBool;
  uint16_t getADC_value_FinalReturn;
  CMOCK_getADC_value_CALLBACK getADC_value_CallbackFunctionPointer;
  int getADC_value_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE getADC_value_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_hardware_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.getADC_value_IgnoreBool)
    Mock.getADC_value_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_getADC_value);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.getADC_value_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.getADC_value_CallbackFunctionPointer != NULL)
    Mock.getADC_value_CallInstance = CMOCK_GUTS_NONE;
}

void mock_hardware_Init(void)
{
  mock_hardware_Destroy();
}

void mock_hardware_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.getADC_value_CallbackFunctionPointer = NULL;
  Mock.getADC_value_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

uint16_t getADC_value(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getADC_value_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getADC_value);
  cmock_call_instance = (CMOCK_getADC_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getADC_value_CallInstance);
  Mock.getADC_value_CallInstance = CMock_Guts_MemNext(Mock.getADC_value_CallInstance);
  if (Mock.getADC_value_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.getADC_value_FinalReturn;
    Mock.getADC_value_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.getADC_value_CallbackFunctionPointer != NULL)
  {
    return Mock.getADC_value_CallbackFunctionPointer(Mock.getADC_value_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void getADC_value_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getADC_value_CALL_INSTANCE));
  CMOCK_getADC_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_getADC_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getADC_value_CallInstance = CMock_Guts_MemChain(Mock.getADC_value_CallInstance, cmock_guts_index);
  Mock.getADC_value_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.getADC_value_IgnoreBool = (int)1;
}

void getADC_value_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getADC_value_CALL_INSTANCE));
  CMOCK_getADC_value_CALL_INSTANCE* cmock_call_instance = (CMOCK_getADC_value_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getADC_value_CallInstance = CMock_Guts_MemChain(Mock.getADC_value_CallInstance, cmock_guts_index);
  Mock.getADC_value_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void getADC_value_StubWithCallback(CMOCK_getADC_value_CALLBACK Callback)
{
  Mock.getADC_value_IgnoreBool = (int)0;
  Mock.getADC_value_CallbackFunctionPointer = Callback;
}

